//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import javax.swing.*;
import java.awt.*;

public class Info extends JPanel {

    public Info() {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException |
                 UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Intro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        final int MAX = 1000;
        //construct components
        JLabel depositText = new JLabel("Deposit");
        JLabel howMuchText = new JLabel("How much do you want to deposit?");
        JSlider slider = new JSlider(0, MAX);
        JButton back = new JButton("Back");
        JButton confirm = new JButton("Confirm");

        //set components properties
        slider.setOrientation(JSlider.HORIZONTAL);
        slider.setMinorTickSpacing(MAX / 20);
        slider.setMajorTickSpacing(MAX / 10);
        slider.setPaintTicks(true);
        slider.setPaintLabels(true);

        //adjust size and set layout
        setPreferredSize(new Dimension(590, 590));
        setLayout(null);

        //add components
        add(depositText);
        add(howMuchText);
        add(slider);
        add(back);
        add(confirm);

        //set component bounds (only needed by Absolute Positioning)
        depositText.setBounds(272, 55, 45, 20);
        howMuchText.setBounds(197, 105, 195, 25);
        slider.setBounds(100, 170, 390, 45);
        back.setBounds(145, 280, 100, 25);
        confirm.setBounds(345, 280, 100, 25);
    }


    public static void main(String[] args) {
        JFrame frame = new JFrame("Deposit");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add(new Deposit());
        frame.pack();
        frame.setVisible(true);
    }
}