/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Pants
 */
public class TabbedPaneNew extends javax.swing.JFrame {

    /**
     * Creates new form TabbedPane
     */
    public TabbedPaneNew() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        TabbedPane = new javax.swing.JTabbedPane();
        HomeTab = new javax.swing.JPanel();
        WelcomePane = new javax.swing.JPanel();
        VariableWelcomeText = new javax.swing.JLabel();
        ButtonPane = new javax.swing.JPanel();
        DepositButton = new javax.swing.JButton();
        WithdrawButton = new javax.swing.JButton();
        TransferButton = new javax.swing.JButton();
        InfoButton = new javax.swing.JButton();
        DepositTab = new javax.swing.JPanel();
        DepositQuestionPanel = new javax.swing.JPanel();
        DepositQuestionText = new javax.swing.JLabel();
        DepositSliderPanel = new javax.swing.JPanel();
        DepositSlider = new javax.swing.JSlider();
        DepositConfirmButton = new javax.swing.JButton();
        VariableDepositText = new javax.swing.JLabel();
        WithdrawTab = new javax.swing.JPanel();
        WithdrawQuestionPanel = new javax.swing.JPanel();
        WithdrawQuestionText = new javax.swing.JLabel();
        WithdrawPanel = new javax.swing.JPanel();
        WithdrawSlider = new javax.swing.JSlider();
        WithdrawConfirmButton = new javax.swing.JButton();
        VariableWithdrawText = new javax.swing.JLabel();
        TransferTab = new javax.swing.JPanel();
        TransferDepositPanel = new javax.swing.JPanel();
        TransferQuestionText = new javax.swing.JLabel();
        TransferPanel = new javax.swing.JPanel();
        TransferSlider = new javax.swing.JSlider();
        VariableTransferText1 = new javax.swing.JLabel();
        TransfereeAccountPanel = new javax.swing.JPanel();
        TransfereeAccountText = new javax.swing.JLabel();
        TransfereeAccountField = new javax.swing.JTextField();
        TransferConfirmButton = new javax.swing.JButton();
        AccountTab = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TabbedPane.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        HomeTab.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        WelcomePane.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        VariableWelcomeText.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        VariableWelcomeText.setText("Welcome User");

        javax.swing.GroupLayout WelcomePaneLayout = new javax.swing.GroupLayout(WelcomePane);
        WelcomePane.setLayout(WelcomePaneLayout);
        WelcomePaneLayout.setHorizontalGroup(
                WelcomePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WelcomePaneLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(VariableWelcomeText)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        WelcomePaneLayout.setVerticalGroup(
                WelcomePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(WelcomePaneLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(VariableWelcomeText)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ButtonPane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 12))); // NOI18N
        ButtonPane.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        DepositButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        DepositButton.setText("Deposit");
        DepositButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositButtonActionPerformed(evt);
            }
        });

        WithdrawButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        WithdrawButton.setText("Withdraw");
        WithdrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WithdrawButtonActionPerformed(evt);
            }
        });

        TransferButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        TransferButton.setText("Transfer");

        InfoButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        InfoButton.setText("Account Information");

        javax.swing.GroupLayout ButtonPaneLayout = new javax.swing.GroupLayout(ButtonPane);
        ButtonPane.setLayout(ButtonPaneLayout);
        ButtonPaneLayout.setHorizontalGroup(
                ButtonPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ButtonPaneLayout.createSequentialGroup()
                                .addContainerGap(14, Short.MAX_VALUE)
                                .addComponent(DepositButton)
                                .addGap(18, 18, 18)
                                .addComponent(WithdrawButton)
                                .addGap(18, 18, 18)
                                .addComponent(TransferButton)
                                .addGap(18, 18, 18)
                                .addComponent(InfoButton)
                                .addContainerGap(13, Short.MAX_VALUE))
        );
        ButtonPaneLayout.setVerticalGroup(
                ButtonPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ButtonPaneLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(ButtonPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(DepositButton)
                                        .addComponent(WithdrawButton)
                                        .addComponent(TransferButton)
                                        .addComponent(InfoButton))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout HomeTabLayout = new javax.swing.GroupLayout(HomeTab);
        HomeTab.setLayout(HomeTabLayout);
        HomeTabLayout.setHorizontalGroup(
                HomeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(HomeTabLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(HomeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ButtonPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(WelcomePane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        HomeTabLayout.setVerticalGroup(
                HomeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(HomeTabLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(WelcomePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(ButtonPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TabbedPane.addTab("Home", HomeTab);

        DepositTab.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        DepositQuestionPanel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        DepositQuestionText.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        DepositQuestionText.setText("How much do you want to deposit?");

        javax.swing.GroupLayout DepositQuestionPanelLayout = new javax.swing.GroupLayout(DepositQuestionPanel);
        DepositQuestionPanel.setLayout(DepositQuestionPanelLayout);
        DepositQuestionPanelLayout.setHorizontalGroup(
                DepositQuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(DepositQuestionPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DepositQuestionText)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DepositQuestionPanelLayout.setVerticalGroup(
                DepositQuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(DepositQuestionPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DepositQuestionText)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DepositSliderPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Deposit", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 12))); // NOI18N
        DepositSliderPanel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        DepositSlider.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        DepositSlider.setMajorTickSpacing(10);
        DepositSlider.setMinorTickSpacing(5);
        DepositSlider.setPaintLabels(true);
        DepositSlider.setPaintTicks(true);
        DepositSlider.setValue(50);

        DepositConfirmButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        DepositConfirmButton.setText("Confirm");

        VariableDepositText.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        VariableDepositText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VariableDepositText.setText("$0");

        javax.swing.GroupLayout DepositSliderPanelLayout = new javax.swing.GroupLayout(DepositSliderPanel);
        DepositSliderPanel.setLayout(DepositSliderPanelLayout);
        DepositSliderPanelLayout.setHorizontalGroup(
                DepositSliderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(DepositSliderPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(DepositSliderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(DepositSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                                        .addGroup(DepositSliderPanelLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(DepositConfirmButton)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(VariableDepositText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        DepositSliderPanelLayout.setVerticalGroup(
                DepositSliderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(DepositSliderPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(VariableDepositText)
                                .addGap(18, 18, 18)
                                .addComponent(DepositSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(DepositConfirmButton)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DepositTabLayout = new javax.swing.GroupLayout(DepositTab);
        DepositTab.setLayout(DepositTabLayout);
        DepositTabLayout.setHorizontalGroup(
                DepositTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(DepositTabLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(DepositTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DepositTabLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(DepositQuestionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(DepositSliderPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        DepositTabLayout.setVerticalGroup(
                DepositTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(DepositTabLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(DepositQuestionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(DepositSliderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TabbedPane.addTab("Deposit", DepositTab);

        WithdrawTab.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        WithdrawQuestionPanel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        WithdrawQuestionText.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        WithdrawQuestionText.setText("How much do you want to withdraw?");

        javax.swing.GroupLayout WithdrawQuestionPanelLayout = new javax.swing.GroupLayout(WithdrawQuestionPanel);
        WithdrawQuestionPanel.setLayout(WithdrawQuestionPanelLayout);
        WithdrawQuestionPanelLayout.setHorizontalGroup(
                WithdrawQuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(WithdrawQuestionPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(WithdrawQuestionText)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        WithdrawQuestionPanelLayout.setVerticalGroup(
                WithdrawQuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(WithdrawQuestionPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(WithdrawQuestionText)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        WithdrawPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Withdraw", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 12))); // NOI18N
        WithdrawPanel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        WithdrawSlider.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        WithdrawSlider.setMajorTickSpacing(10);
        WithdrawSlider.setMinorTickSpacing(5);
        WithdrawSlider.setPaintLabels(true);
        WithdrawSlider.setPaintTicks(true);

        WithdrawConfirmButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        WithdrawConfirmButton.setText("Confirm");

        VariableWithdrawText.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        VariableWithdrawText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VariableWithdrawText.setText("$0");

        javax.swing.GroupLayout WithdrawPanelLayout = new javax.swing.GroupLayout(WithdrawPanel);
        WithdrawPanel.setLayout(WithdrawPanelLayout);
        WithdrawPanelLayout.setHorizontalGroup(
                WithdrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WithdrawPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(WithdrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(VariableWithdrawText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, WithdrawPanelLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(WithdrawConfirmButton)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(WithdrawSlider, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE))
                                .addContainerGap())
        );
        WithdrawPanelLayout.setVerticalGroup(
                WithdrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(WithdrawPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(VariableWithdrawText)
                                .addGap(18, 18, 18)
                                .addComponent(WithdrawSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(WithdrawConfirmButton)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout WithdrawTabLayout = new javax.swing.GroupLayout(WithdrawTab);
        WithdrawTab.setLayout(WithdrawTabLayout);
        WithdrawTabLayout.setHorizontalGroup(
                WithdrawTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(WithdrawTabLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(WithdrawTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(WithdrawTabLayout.createSequentialGroup()
                                                .addGap(0, 131, Short.MAX_VALUE)
                                                .addComponent(WithdrawQuestionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 131, Short.MAX_VALUE))
                                        .addComponent(WithdrawPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        WithdrawTabLayout.setVerticalGroup(
                WithdrawTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(WithdrawTabLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(WithdrawQuestionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(WithdrawPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(140, Short.MAX_VALUE))
        );

        TabbedPane.addTab("Withdraw", WithdrawTab);

        TransferTab.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        TransferDepositPanel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        TransferQuestionText.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        TransferQuestionText.setText("How much do you want to Transfer?");

        javax.swing.GroupLayout TransferDepositPanelLayout = new javax.swing.GroupLayout(TransferDepositPanel);
        TransferDepositPanel.setLayout(TransferDepositPanelLayout);
        TransferDepositPanelLayout.setHorizontalGroup(
                TransferDepositPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(TransferDepositPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TransferQuestionText)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TransferDepositPanelLayout.setVerticalGroup(
                TransferDepositPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(TransferDepositPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TransferQuestionText)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TransferPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Transfer Amount", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 12))); // NOI18N
        TransferPanel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        TransferSlider.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        TransferSlider.setMajorTickSpacing(10);
        TransferSlider.setMinorTickSpacing(5);
        TransferSlider.setPaintLabels(true);
        TransferSlider.setPaintTicks(true);

        VariableTransferText1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        VariableTransferText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VariableTransferText1.setText("$0");

        javax.swing.GroupLayout TransferPanelLayout = new javax.swing.GroupLayout(TransferPanel);
        TransferPanel.setLayout(TransferPanelLayout);
        TransferPanelLayout.setHorizontalGroup(
                TransferPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TransferPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(TransferPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(VariableTransferText1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TransferSlider, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        TransferPanelLayout.setVerticalGroup(
                TransferPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(TransferPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(VariableTransferText1)
                                .addGap(18, 18, 18)
                                .addComponent(TransferSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TransfereeAccountPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Transferee Account", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 12))); // NOI18N
        TransfereeAccountPanel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        TransfereeAccountText.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        TransfereeAccountText.setText("Transferee Account Number");

        TransfereeAccountField.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        TransfereeAccountField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TransfereeAccountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransfereeAccountFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TransfereeAccountPanelLayout = new javax.swing.GroupLayout(TransfereeAccountPanel);
        TransfereeAccountPanel.setLayout(TransfereeAccountPanelLayout);
        TransfereeAccountPanelLayout.setHorizontalGroup(
                TransfereeAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(TransfereeAccountPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(TransfereeAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(TransfereeAccountPanelLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(TransfereeAccountText)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(TransfereeAccountField, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addContainerGap())
        );
        TransfereeAccountPanelLayout.setVerticalGroup(
                TransfereeAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(TransfereeAccountPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(TransfereeAccountText)
                                .addGap(18, 18, 18)
                                .addComponent(TransfereeAccountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TransferConfirmButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        TransferConfirmButton.setText("Confirm");

        javax.swing.GroupLayout TransferTabLayout = new javax.swing.GroupLayout(TransferTab);
        TransferTab.setLayout(TransferTabLayout);
        TransferTabLayout.setHorizontalGroup(
                TransferTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(TransferTabLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(TransferTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(TransferTabLayout.createSequentialGroup()
                                                .addGroup(TransferTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(TransferTabLayout.createSequentialGroup()
                                                                .addGap(0, 128, Short.MAX_VALUE)
                                                                .addComponent(TransferDepositPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 135, Short.MAX_VALUE))
                                                        .addComponent(TransferPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addContainerGap())
                                        .addGroup(TransferTabLayout.createSequentialGroup()
                                                .addComponent(TransfereeAccountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, Short.MAX_VALUE)
                                                .addComponent(TransferConfirmButton)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        TransferTabLayout.setVerticalGroup(
                TransferTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(TransferTabLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(TransferDepositPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(TransferPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(TransferTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(TransferTabLayout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(TransfereeAccountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(TransferTabLayout.createSequentialGroup()
                                                .addGap(60, 60, 60)
                                                .addComponent(TransferConfirmButton)))
                                .addContainerGap(68, Short.MAX_VALUE))
        );

        TabbedPane.addTab("Transfer", TransferTab);

        AccountTab.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        javax.swing.GroupLayout AccountTabLayout = new javax.swing.GroupLayout(AccountTab);
        AccountTab.setLayout(AccountTabLayout);
        AccountTabLayout.setHorizontalGroup(
                AccountTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 488, Short.MAX_VALUE)
        );
        AccountTabLayout.setVerticalGroup(
                AccountTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 457, Short.MAX_VALUE)
        );

        TabbedPane.addTab("Account Information", AccountTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void DepositButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void WithdrawButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void TransfereeAccountFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabbedPaneNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabbedPaneNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabbedPaneNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabbedPaneNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabbedPaneNew().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JPanel AccountTab;
    private javax.swing.JPanel ButtonPane;
    private javax.swing.JButton DepositButton;
    private javax.swing.JButton DepositConfirmButton;
    private javax.swing.JPanel DepositQuestionPanel;
    private javax.swing.JLabel DepositQuestionText;
    private javax.swing.JSlider DepositSlider;
    private javax.swing.JPanel DepositSliderPanel;
    private javax.swing.JPanel DepositTab;
    private javax.swing.JPanel HomeTab;
    private javax.swing.JButton InfoButton;
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JButton TransferButton;
    private javax.swing.JButton TransferConfirmButton;
    private javax.swing.JPanel TransferDepositPanel;
    private javax.swing.JPanel TransferPanel;
    private javax.swing.JLabel TransferQuestionText;
    private javax.swing.JSlider TransferSlider;
    private javax.swing.JPanel TransferTab;
    private javax.swing.JTextField TransfereeAccountField;
    private javax.swing.JPanel TransfereeAccountPanel;
    private javax.swing.JLabel TransfereeAccountText;
    private javax.swing.JLabel VariableDepositText;
    private javax.swing.JLabel VariableTransferText1;
    private javax.swing.JLabel VariableWelcomeText;
    private javax.swing.JLabel VariableWithdrawText;
    private javax.swing.JPanel WelcomePane;
    private javax.swing.JButton WithdrawButton;
    private javax.swing.JButton WithdrawConfirmButton;
    private javax.swing.JPanel WithdrawPanel;
    private javax.swing.JPanel WithdrawQuestionPanel;
    private javax.swing.JLabel WithdrawQuestionText;
    private javax.swing.JSlider WithdrawSlider;
    private javax.swing.JPanel WithdrawTab;
    // End of variables declaration
}
